[build-system]
requires = ["setuptools>=77.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "toastify-ctk"
version = "0.0.2"
description = "Modern toast notifications for CustomTkinter"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"

authors = [
    { name = "Waqas Khan" , email = "waqaskhan0589@gmail.com"}
]

keywords = [
    "customtkinter",
    "toast",
    "notifications",
    "ui",
    "tkinter",
    "toastify-ctk",
    "toastify"
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

dependencies = [
    "customtkinter>=5.2.0"
]

[project.urls]
Homepage = "https://github.com/Waqas-Khan-CodeCanvas/toastify-ctk"
Issues = "https://github.com/Waqas-Khan-CodeCanvas/toastify-ctk/issues"

[tool.setuptools.packages.find]
where = ["src"]